name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Chmod
      run: chmod +x ./build.sh
    - name: Build
      run: ./build.sh github.com/kockicica/gospl
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: artifacts

