name: Go

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Chmod
        run: chmod +x ./build.sh

      - name: Find tag
        id: tagger
        uses: jimschubert/query-tag-action@v1

      - name: Build
        run: ./build.sh gospl
        env:
          CI_COMMIT_TAG: ${{steps.tagger.outputs.tag}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: artifacts

