name: Go

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Chmod
        run: chmod +x ./build.sh

      - name: Find tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        continue-on-error: true
        with:
          commit-ish: 'HEAD'

      - name: Build
        run: ./build.sh gospl
        env:
          CI_COMMIT_TAG: ${{steps.tagger.outputs.tag}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: artifacts

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - use: actions/checkout@v2
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          prerelease_regex: "^beta\\.[[:digit:]]+"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: ./artifacts/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}